apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
  - verbs: ["get", "list", "watch"]
    resources:
      - namespaces
      - pods
    apiGroups: [""]